# -*- coding: utf-8 -*-
"""technical_agent_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XkOoI_cftt-FWPdJs1ojvOQhzZqy4zSS
"""

import json
import nltk
import requests
from pymongo import MongoClient
import google.generativeai as genai
from google.colab import files

class TechnicalAgent:

    def __init__(self, api_key, mongo_url):
        self.api_key = api_key
        self.mongo_url = mongo_url

        genai.configure(api_key=self.api_key)
        nltk.download("stopwords", quiet=True)

        self.client = MongoClient(self.mongo_url)
        self.db = self.client["asian_paints_db"]
        self.products_col = self.db["products"]
        self.rfps_col = self.db["rfps"]

        print("✅ Gemini ready")
        print("✅ Connected to MongoDB Atlas")
        print("Products in DB:", self.products_col.count_documents({}))

    def generate_embedding(self, content: str, model="models/text-embedding-004"):
        try:
            resp = genai.embed_content(
                model=model,
                content=content,
                request_options={"timeout": 120},
            )
            return resp["embedding"]
        except requests.exceptions.ReadTimeout as e:
            print("⏱️ Request timed out:", e)
            return None
        except Exception as e:
            print("❌ Embedding error:", e)
            return None

    def search_products(self, query_embedding, top_k=5):
        if query_embedding is None:
            print("❌ query_embedding is None")
            return []

        pipeline = [
            {
                "$vectorSearch": {
                    "index": "default",
                    "queryVector": query_embedding,
                    "path": "embedding",
                    "numCandidates": 50,
                    "limit": top_k,
                }
            },
            {
                "$project": {
                    "_id": 0,
                    "sku": 1,
                    "name": 1,
                    "description": 1,
                    "_score": {"$meta": "vectorSearchScore"},
                }
            },
        ]

        return list(self.products_col.aggregate(pipeline))

    def update_product_embeddings(self):
        docs = list(self.products_col.find({}))
        print("Found products:", len(docs))

        updated = 0
        for doc in docs:
            desc = doc.get("description", "")
            if not desc:
                print("⚠️ Skipping (no description):", doc.get("sku"))
                continue

            emb = self.generate_embedding(desc)
            if emb is None:
                print("⚠️ Failed embedding for:", doc.get("sku"))
                continue

            self.products_col.update_one(
                {"_id": doc["_id"]},
                {"$set": {"embedding": emb}}
            )
            updated += 1

        print("✅ Product embeddings updated:", updated)
        print("Products with embedding:",
              self.products_col.count_documents({"embedding": {"$exists": True}}))

    def upload_and_store_rfp(self):
        print("📂 Upload RFP JSON file")
        uploaded = files.upload()

        rfp_filename = list(uploaded.keys())[0]

        with open(rfp_filename, "r") as f:
            rfp_json = json.load(f)

        print("✅ Loaded RFP JSON:")
        print(rfp_json)

        rfp_text = json.dumps(rfp_json, indent=2)

        rfp_embedding = self.generate_embedding(rfp_text)
        print("Embedding length:", len(rfp_embedding) if rfp_embedding else None)

        rfp_id = self.rfps_col.insert_one(
            {
                "rfp_data": rfp_json,
                "rfp_text": rfp_text,
                "embedding": rfp_embedding,
            }
        ).inserted_id

        print("✅ RFP stored in MongoDB with _id:", rfp_id)
        return rfp_embedding

    def match_rfp_to_products(self, rfp_embedding, top_k=5):
        matches = self.search_products(rfp_embedding, top_k)

        print("\n===== MATCHING PRODUCTS =====\n")
        for m in matches:
            print("Name:", m.get("name"))
            print("SKU:", m.get("sku"))
            print("Score:", m.get("_score"))
            print("-" * 40)

        return matches


# ---- RUN THE AGENT ----

API_KEY = "AIzaSyC2Ihcm8HYa26o9st936njU12EwrwaX37w"   # replace this
MONGO_URL = "mongodb+srv://sharibhasnain8_db_user:6P.Mgj#WB*wDULr@sharib.urytptj.mongodb.net/?appName=Sharib"


agent = TechnicalAgent(API_KEY, MONGO_URL)

agent.update_product_embeddings()

rfp_embedding = agent.upload_and_store_rfp()

agent.match_rfp_to_products(rfp_embedding)
