# Master list of all event types
RFP_RECEIVED = "RFP_RECEIVED"

TECHNICAL_DONE = "TECHNICAL_DONE"
PRICING_DONE = "PRICING_DONE"
PROPOSAL_DONE = "PROPOSAL_DONE"
LEGAL_APPROVED = "LEGAL_APPROVED"
HUMAN_APPROVED = "HUMAN_APPROVED"

# Event mapping (pipeline order)
NEXT_EVENT = {
    RFP_RECEIVED: TECHNICAL_DONE,
    TECHNICAL_DONE: PRICING_DONE,
    PRICING_DONE: PROPOSAL_DONE,
    PROPOSAL_DONE: LEGAL_APPROVED,
    LEGAL_APPROVED: HUMAN_APPROVED,
}
