# -*- coding: utf-8 -*-
"""technical_agent_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XkOoI_cftt-FWPdJs1ojvOQhzZqy4zSS
"""

# !pip install -y google-ai-generativelanguage
# !pip install -U google-generativeai pymongo nltk

import json
import nltk
from pymongo import MongoClient
from google.colab import userdata
import google.generativeai as genai

# -------- Gemini API key --------
# API_KEY = userdata.get("GEMINI_API_KEY")
API_KEY = "AIzaSyCDqiSCiozPGyTSQqLYhPGXz_DdjkqVYuk"
if not API_KEY:
    raise RuntimeError("Set GEMINI_API_KEY in Colab (Settings → Variables).")

genai.configure(api_key=API_KEY)

# -------- NLTK (optional, for later if needed) --------
nltk.download("stopwords", quiet=True)

# -------- MongoDB Atlas connection --------
MONGO_URL = "mongodb+srv://sharibhasnain8_db_user:V9trVf1wTe8GDUuW@sharib.urytptj.mongodb.net/?retryWrites=true&w=majority&appName=Sharib"

client = MongoClient(MONGO_URL)
db = client["asian_paints_db"]
products_col = db["products"]
rfps_col = db["rfps"]   # new collection for RFPs

print("✅ Gemini ready")
print("✅ Connected to MongoDB Atlas")
print("Products in DB:", products_col.count_documents({}))

import requests

# ---- 1. Text Embedding (Gemini) ----
def generate_embedding(content: str, model: str = "models/text-embedding-004"):
    """
    Returns a list[float] embedding for the given content.
    """
    try:
        resp = genai.embed_content(
            model=model,
            content=content,
            request_options={"timeout": 120},
        )
        return resp["embedding"]
    except requests.exceptions.ReadTimeout as e:
        print("⏱️ Request timed out:", e)
        return None
    except Exception as e:
        print("❌ Embedding error:", e)
        return None

# ---- 2. Product vector search using MongoDB $vectorSearch ----
def search_products_by_embedding(query_embedding, top_k: int = 5):
    if query_embedding is None:
        print("❌ query_embedding is None")
        return []

    pipeline = [
        {
            "$vectorSearch": {
                "index": "default",              # <--- your index name
                "queryVector": query_embedding,
                "path": "embedding",             # <--- field in product docs
                "numCandidates": 50,
                "limit": top_k,
            }
        },
        {
            "$project": {
                "_id": 0,
                "sku": 1,
                "name": 1,
                "description": 1,
                "_score": {"$meta": "vectorSearchScore"},
            }
        },
    ]

    return list(products_col.aggregate(pipeline))

docs = list(products_col.find({}))
print("Found products:", len(docs))

updated = 0

for doc in docs:
    desc = doc.get("description", "")
    if not desc:
        print("⚠️ Skipping (no description):", doc.get("sku"))
        continue

    emb = generate_embedding(desc)
    if emb is None:
        print("⚠️ Failed embedding for:", doc.get("sku"))
        continue

    products_col.update_one(
        {"_id": doc["_id"]},
        {"$set": {"embedding": emb}}
    )
    updated += 1

print("✅ Product embeddings updated:", updated)
print("Products with embedding:",
      products_col.count_documents({"embedding": {"$exists": True}}))

from google.colab import files

print("📂 Upload RFP JSON file")
uploaded = files.upload()
rfp_filename = list(uploaded.keys())[0]

with open(rfp_filename, "r") as f:
    rfp_json = json.load(f)

print("✅ Loaded RFP JSON:")
print(rfp_json)

# Convert full JSON to text string for embedding and summary
rfp_text = json.dumps(rfp_json, indent=2)

rfp_embedding = generate_embedding(rfp_text)
print("Embedding length:", len(rfp_embedding) if rfp_embedding else None)

rfp_id = rfps_col.insert_one(
    {
        "rfp_data": rfp_json,
        "rfp_text": rfp_text,
        "embedding": rfp_embedding,
    }
).inserted_id

print("✅ RFP stored in MongoDB with _id:", rfp_id)

matches = search_products_by_embedding(rfp_embedding, top_k=5)

print("\n===== MATCHING PRODUCTS =====\n")
for m in matches:
    print("Name:", m.get("name"))
    print("SKU:", m.get("sku"))
    print("Score:", m.get("_score"))
    print("-" * 40)